export const ERR_OK = '1';
export const NEW_ORDER = '1';
export const BACK_ORDER = '2';
export const HANDLING_ORDER = '3';
export const HISTORY_ORDER = '4';
export const ABNORMAL_ORDER = '6';
export const INIT_PAGER = 1; // 初始化当前页
export const ITEMHEIGHT = 112; // 单个列表高度
export const TOPBOTTOMSIZE = 246; // 头部和底部高度
export const OFFSETHEIGHT = 0; // 预留高度
export const DATEPICKERHEIGHT = 53; // 日期查找高度
export const TODAY = new Date();
export const TOMORROW = new Date(new Date().getTime() + 24 * 60 * 60 * 1000);
