export default {
  vuex: 'posInfo',
  url: '/canyin/pos/reception/receptionbusiness/receptionbusinessbaseinfov2',
  data: [{
    key: 'currentLanguage',
    type: String,
    text: '国际化：当前语言',
  }, {
    key: 'websocketContextPath',
    type: String,
    text: 'WebSocket路径',
  }, {
    key: 'address',
    type: String,
    text: '门店地址',
  }, {
    key: 'contactTel',
    type: String,
    text: '门店联系电话',
  }, {
    key: 'controlMode',
    type: String,
    text: '前台营业操作模式',
  }, {
    key: 'createShopName',
    type: String,
    text: '门店名称',
  }, {
    key: 'isDebugMode',
    type: Boolean,
    text: 'Debug模式',
  }, {
    key: 'shopId',
    type: Number,
    test: '门店ID',
  }, {
    key: 'slogan',
    type: String,
    text: '广告语',
  }, {
    key: 'title',
    type: String,
    text: '标题',
  }, {
    key: 'user',
    type: Object,
    text: '用户信息',
  }, {
    key: 'version',
    type: String,
    text: '版本',
  }, {
    key: 'isKeBiDe',
    type: Boolean,
    text: '是否开启客必得增值',
  }, {
    key: 'isKeBiDeDeposit',
    type: Boolean,
    text: '是否开启客必得押金',
  }, {
    key: 'isHaveEndBill',
    type: Boolean,
    text: '结班是否允许有未结账客位',
  }, {
    key: 'isMoneyInput',
    type: Boolean,
    text: '是否显示金额录入窗口',
  }, {
    key: 'isNPosShowMoney',
    type: Boolean,
    text: '仅在收银模式的终端显示金额',
  }, {
    key: 'printWhenEndJob',
    type: Boolean,
    text: '不打印结班报表',
  }, {
    key: 'isOnlyEndJob',
    type: Boolean,
    text: '结班是否显示结班信息',
  }, {
    key: 'isShowBillSerial',
    type: Boolean,
    text: '状态栏区域显示开台信息',
  }, {
    key: 'isShowTotalMoney',
    type: Boolean,
    text: '状态栏区域显示已结金额和未结金额',
  }, {
    key: 'doesInputBillModeDisplayFooter',
    type: Boolean,
    text: '录单模式状态栏是否显示统计信息',
  }, {
    key: 'isAllowUpdatePosModeWhenOpening',
    type: Boolean,
    text: '登录系统时允许对收银/快餐模式进行切换',
  }, {
    key: 'isEnableHandwritingBoard',
    type: Boolean,
    text: '启用手写板',
  }, {
    key: 'isEnableQWEKeyboard',
    type: Boolean,
    text: '是否启用全键盘',
  }, {
    key: 'isEnableYiPan',
    type: Boolean,
    text: '是否启用易盘',
  }, {
    key: 'isEnableZhiPan',
    type: Boolean,
    text: '是否启用智盘',
  }, {
    key: 'isFingerprintMandatory',
    type: Boolean,
    text: '优先使用指纹授权',
  }, {
    key: 'isFirstLogin',
    type: Boolean,
    text: '是否是首次登录',
  }, {
    key: 'isOpenLockScreen',
    type: Boolean,
    text: '启用锁屏功能',
  }, {
    key: 'isOrderPrint',
    type: Boolean,
    text: '是否启用指令打印',
  }, {
    key: 'lockScreenWaitingTime',
    type: Number,
    text: '自动锁屏等待时间（单位秒）',
  }, {
    key: 'nowTime',
    type: String,
    text: '当前系统时间',
  }, {
    key: 'openingCashierPosCount',
    type: Number,
    text: '正在运行的收银终端数量',
  }, {
    key: 'orderCount',
    type: Number,
    text: '确认到店的预点单数量',
  }, {
    key: 'parallelPrinter',
    type: Object,
    text: '打印机信息',
  }, {
    key: 'code',
    type: String,
    text: '当前终端代码',
  }, {
    key: 'id',
    type: String,
    text: '当前终端ID',
  }, {
    key: 'yipanList',
    type: Array,
    text: '易盘数据',
    columns: [{
      key: 'frame',
      text: 'frame',
      width: 80,
    }, {
      key: 'panType',
      text: 'panType',
      width: 100,
    }, {
      key: 'port',
      text: '串口号',
      width: 80,
    }, {
      key: 'posId',
      text: '终端ID',
      width: 180,
    }, {
      key: 'rate',
      text: '波特率',
      width: 80,
    }],
  }, {
    key: 'zhipanList',
    type: Array,
    text: '智盘数据',
  }, {
    key: 'reserveUnpaid',
    type: Boolean,
    text: '是否开启预订挂账',
  }, {
    key: 'isMingChenEnable',
    type: Boolean,
    text: '是否开启冥晨对接',
  }, {
    key: 'isPrintBillAfterAddOrder',
    type: Boolean,
    text: '是否加单后打印客用单',
  }],
};
