export default {
  vuex: 'outDeviceSetting',
  url: '/canyin/pos/reception/receptionbusiness/receptionbusinesssyssettingv2',
  data: [{
    key: 'isAccounAutoOpenCashbox',
    type: Boolean,
    text: '确认结算时自动打开钱箱',
  }, {
    key: 'isEndOpenCashbox',
    type: Boolean,
    text: '结班后自动打开钱箱',
  }, {
    key: 'isOthersOpenCashbox',
    type: Boolean,
    text: '加/退单后自动打开钱箱',
  }, {
    key: 'isStartOpenCashbox',
    type: Boolean,
    text: '开班后自动打开钱箱',
  }, {
    key: 'scaleItemCodeLength',
    type: Number,
    text: '电子秤扫描条码品项代码长度',
  }, {
    key: 'scaleItemCodeStart',
    type: Number,
    text: '电子秤扫描条码品项代码开始位置',
  }, {
    key: 'scaleItemQuantityIntegerLength',
    type: Number,
    text: '电子秤扫描条码品项数量整数部分长度',
  }, {
    key: 'scaleItemQuantityLength',
    type: Number,
    text: '电子秤扫描条码品项数量长度',
  }, {
    key: 'scaleItemQuantityStart',
    type: Number,
    text: '电子秤扫描条码品项数量开始位置',
  }],
};
