export default {
  vuex: 'posTakeout',
  url: '/canyin/pos/reception/receptionbusiness/receptionbusinesssyssettingv2',
  data: [{
    key: 'enable',
    type: Boolean,
    text: '是否开启外卖',
  }, {
    key: 'autoMakeTime',
    type: Number,
    text: '自动制作提前时间',
  }, {
    key: 'isAutoConfim',
    type: Boolean,
    text: '是否自动接单',
  }, {
    key: 'isAutoSettleGlobal',
    type: Boolean,
    text: '是否自动结算',
  }, {
    key: 'isAutoSettleNoPay',
    type: Boolean,
    text: 'isAutoSettleNoPay',
  }, {
    key: 'isPrintSettle',
    type: Boolean,
    text: '是否打印结账单',
  }, {
    key: 'lunchboxItemId',
    type: String,
    text: '餐盒费品项ID',
  }, {
    key: 'psFeeItemID',
    type: String,
    text: '配送费品项',
  }, {
    key: 'haveTakeoutPhone',
    type: Boolean,
    text: '是否启用电话外卖',
  }, {
    key: 'takeoutDeviceType',
    type: String,
    text: '电话设备类型',
  }, {
    key: 'isNewTakeoutPhoneOrder',
    type: Boolean,
    text: '是否开启电话外卖单业务',
  }],
};
